<?php
const
    TITLE         = 'title',
    APPID         = 'appid',
    APP_ID        = 'appId',
    APP_SECRET    = 'appSecret',
    TOKEN         = 'token',
    OPENID        = 'openid',
    OPENNAME      = 'openName',
    OPEN_TYPE     = 'open_type',
    OPEN_ACCOUNT  = 'open_account',
    FOLLOW_STATUS = 'follow_status',
    FOLLOW_TIME   = 'follow_time',
    UNFOLLOW_TIME = 'unfollow_time',
    REDIRECT_URI  = 'redirect_uri',
    RESPONSE_TYPE = 'response_type',
    CODE          = 'code',
    MSG           = 'msg',
    DATA          = 'data',
    SCOPE         = 'scope',
    STATE         = 'state',
    NAME          = 'name',
    TYPE          = 'type',
    VIEW          = 'view',
    URL           = 'url',
    SUB_BUTTON    = 'sub_button';